### ISSUE TITLE
KVP in ROS 1

### ISSUE THREAD

**Issue by ghost** [itk-thrivaldi/kuka_kvp_hw_interface#4]
Not actually a issue, more a question..sorry if wrong location. just if you have test it in ROS 1 (knowing that i'm willing to use it with kuka krc4 controller with ROS 1) ?
Thank you in advance

**Comment by mahaarbo** [comment]
This package was developed for use with ROS Kinetic Kame, and hasn't been updated for any later versions.
It was tested with a KUKA KRC2, but KVP has been used with KRC4 by others, and I think it should work.
